spring.application.name=batch-xml-kafka-vt

# Habilita Virtual Threads no Spring Boot
spring.threads.virtual.enabled=true

# Kafka Config
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.LongSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.template.default-topic=customer-processed-topic

spring.datasource.hikari.maximum-pool-size=50

# Batch
# Usando pasta tempor�ria do Linux
app.batch.input-dir=/tmp/spring-batch/input
app.batch.output-dir=/tmp/spring-batch/output
app.batch.partition-size=10
